VERSION 0.8
ARG --global debian

build-container:
    ARG TOKIO_WORKER_THREADS
    FROM ../base+container --debian=$debian
    COPY (../..+build/lightway-server --debian=$debian) .
    COPY --dir ../certs+server/* certs/
    COPY --dir server_config.yaml docker-entrypoint.sh .
    HEALTHCHECK --interval=1s --timeout=1s --start-period=0s --retries=3 CMD [ -n "$(ss -HOlutn sport = :${SERVER_PORT:-443})" ]
    IF [ -n "$TOKIO_WORKER_THREADS" ]
        ENV TOKIO_WORKER_THREADS=$TOKIO_WORKER_THREADS
    END
    ENTRYPOINT ["/docker-entrypoint.sh"]

save-container:
    FROM +build-container --debian=$debian
    SAVE IMAGE lightway-test-server:latest
