VERSION 0.8
ARG --global debian

build-container:
    ARG TOKIO_WORKER_THREADS
    FROM ../base+container --debian=$debian
    COPY (../..+build/lightway-client --debian=$debian) .
    COPY --dir ../certs+client/* tests/certs/
    COPY --dir --chmod 0660 client_config.yaml .
    COPY --dir docker-entrypoint.sh run-test-inside.sh .
    HEALTHCHECK --interval=1s --timeout=1s --start-period=0s --retries=30 CMD ping -c1 nginx
    IF [ -n "$TOKIO_WORKER_THREADS" ]
        ENV TOKIO_WORKER_THREADS=$TOKIO_WORKER_THREADS
    END
    ENTRYPOINT ["/docker-entrypoint.sh"]

save-container:
    FROM +build-container --debian=$debian
    SAVE IMAGE lightway-test-client:latest
