VERSION 0.8
ARG --global debian

build-container:
    FROM ../base+container --debian=$debian
    COPY (../..+build/lightway-client --debian=$debian) .
    COPY --dir ../certs+client/* certs/
    COPY --dir client_config.yaml docker-entrypoint.sh run-test-inside.sh .
    HEALTHCHECK --interval=1s --timeout=1s --start-period=0s --retries=30 CMD ping -c1 nginx
    ENTRYPOINT ["/docker-entrypoint.sh"]

save-container:
    FROM +build-container --debian=$debian
    SAVE IMAGE lightway-test-client:latest
